#!/bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/launch.sh
$HOME/.config/bspwm/launch-bar.sh

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 󰖟    󱛊 
# bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap           7
# bspc config top_padding	     28
bspc config focused_border_color '#4682B4'
		
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle  	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a librewolf-default state=pseudo_tiled desktop='^1'
bspc rule -a Mullvad Browser state=pseudo_tiled
bspc rule -a Windscribe2 state=pseudo_tiled desktop='^6'
bspc rule -a Brave-browser desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating
bspc rule -a TelegramDesktop desktop='^3'
